# Generated by Django 5.1.7 on 2025-03-24 08:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_department_department_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='work_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ПН', 'ПН'), ('ВТ', 'ВТ'), ('СР', 'СР'), ('ЧТ', 'ЧТ'), ('ПТ', 'ПТ'), ('СБ', 'СБ')], max_length=32),
        ),
    ]
