# Generated by Django 5.1.7 on 2025-03-27 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_alter_feedback_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_doctor', to='hospital_app.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_patient', to='hospital_app.patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_department', to='hospital_app.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(related_name='doctor_specialty', to='hospital_app.specialty'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_feed', to='hospital_app.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_patient', to='hospital_app.patient'),
        ),
    ]
