# Generated by Django 5.1.7 on 2025-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_rename_shift_and_doctor_shift_end_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctor_specialty', to='hospital_app.specialty'),
        ),
    ]
